### ISSUE TITLE
[suggestion] Support windows platform test.

### ISSUE THREAD

**Issue by MaoMao-zk** [MaoMao-zk/Introduction-to-Algorithms#10]

**Comment by maomao9003** [comment]
https://github.com/maomao9003/Introduction-of-Algorithms/commit/58e60f85bbdb1e5aed35a8be9da68649f92bafbd
https://github.com/maomao9003/Introduction-of-Algorithms/commit/171e2a5987bf2b67030cc31380d268879a71e4b9
